<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MenuItemSeeder extends Seeder
{
    public function run(): void
    {
        // category_id => name (matches CategorySeeder order)
        // 1 = Noodles & Pasta | 2 = Momos | 3 = Snacks & Fries
        // 4 = Maggi | 5 = Beverages | 6 = Coffee & Hot Drinks

        $items = [

            /* ─── Noodles & Pasta (category_id: 1) ─── */
            [
                'category_id'       => 1,
                'name'              => 'Classic Masala Ramen',
                'description'       => 'Rich masala broth with soft-boiled egg, noodles, spring onion and nori',
                'price'             => 149.00,
                'food_type'         => 'non_veg',
                'is_bestseller'     => true,
                'prep_time_minutes' => 12,
                'tags'              => json_encode(['spicy', 'bestseller']),
            ],
            [
                'category_id'       => 1,
                'name'              => 'Veg Ramen Bowl',
                'description'       => 'Umami vegetable broth with tofu, mushrooms, corn and ramen noodles',
                'price'             => 129.00,
                'food_type'         => 'veg',
                'is_featured'       => true,
                'prep_time_minutes' => 12,
                'tags'              => json_encode(['healthy', 'veg']),
            ],
            [
                'category_id'       => 1,
                'name'              => 'Spicy Chicken Ramen',
                'description'       => 'Fiery red broth with pulled chicken, bamboo shoots and chilli oil',
                'price'             => 169.00,
                'food_type'         => 'non_veg',
                'prep_time_minutes' => 12,
                'tags'              => json_encode(['spicy', 'chicken']),
            ],
            [
                'category_id'       => 1,
                'name'              => 'Arrabbiata Pasta',
                'description'       => 'Penne in spicy tomato-garlic sauce topped with parmesan',
                'price'             => 139.00,
                'food_type'         => 'veg',
                'is_bestseller'     => true,
                'prep_time_minutes' => 15,
                'tags'              => json_encode(['pasta', 'italian', 'veg']),
            ],
            [
                'category_id'       => 1,
                'name'              => 'White Sauce Pasta',
                'description'       => 'Creamy béchamel pasta with sautéed mushrooms and herbs',
                'price'             => 149.00,
                'food_type'         => 'veg',
                'prep_time_minutes' => 15,
                'tags'              => json_encode(['pasta', 'creamy']),
            ],
            [
                'category_id'       => 1,
                'name'              => 'Pesto Chicken Pasta',
                'description'       => 'Fusilli tossed in basil pesto with grilled chicken and cherry tomatoes',
                'price'             => 179.00,
                'food_type'         => 'non_veg',
                'is_featured'       => true,
                'prep_time_minutes' => 15,
                'tags'              => json_encode(['pasta', 'chicken', 'pesto']),
            ],

            /* ─── Momos (category_id: 2) ─── */
            [
                'category_id'       => 2,
                'name'              => 'Steamed Veg Momos (6 pcs)',
                'description'       => 'Classic steamed dumplings stuffed with spiced cabbage and carrots, served with red chutney',
                'price'             => 89.00,
                'food_type'         => 'veg',
                'is_bestseller'     => true,
                'prep_time_minutes' => 15,
                'tags'              => json_encode(['steamed', 'veg', 'bestseller']),
            ],
            [
                'category_id'       => 2,
                'name'              => 'Fried Veg Momos (6 pcs)',
                'description'       => 'Crispy pan-fried dumplings with veg filling and smoky chilli dip',
                'price'             => 99.00,
                'food_type'         => 'veg',
                'prep_time_minutes' => 15,
                'tags'              => json_encode(['fried', 'veg', 'crispy']),
            ],
            [
                'category_id'       => 2,
                'name'              => 'Steamed Chicken Momos (6 pcs)',
                'description'       => 'Juicy chicken-filled steamed dumplings with classic tomato-chilli chutney',
                'price'             => 109.00,
                'food_type'         => 'non_veg',
                'is_bestseller'     => true,
                'prep_time_minutes' => 15,
                'tags'              => json_encode(['steamed', 'chicken', 'bestseller']),
            ],
            [
                'category_id'       => 2,
                'name'              => 'Fried Chicken Momos (6 pcs)',
                'description'       => 'Golden fried chicken momos with mayo-chilli dip',
                'price'             => 119.00,
                'food_type'         => 'non_veg',
                'prep_time_minutes' => 15,
                'tags'              => json_encode(['fried', 'chicken']),
            ],
            [
                'category_id'       => 2,
                'name'              => 'Tandoori Momos (6 pcs)',
                'description'       => 'Charcoal-grilled momos marinated in spiced yogurt, served with mint chutney',
                'price'             => 129.00,
                'food_type'         => 'veg',
                'is_featured'       => true,
                'prep_time_minutes' => 18,
                'tags'              => json_encode(['tandoori', 'grilled', 'veg']),
            ],
            [
                'category_id'       => 2,
                'name'              => 'Paneer Momos (6 pcs)',
                'description'       => 'Steamed momos stuffed with spiced paneer and bell peppers',
                'price'             => 119.00,
                'food_type'         => 'veg',
                'prep_time_minutes' => 15,
                'tags'              => json_encode(['paneer', 'veg']),
            ],

            /* ─── Snacks & Fries (category_id: 3) ─── */
            [
                'category_id'       => 3,
                'name'              => 'Classic Salted Fries',
                'description'       => 'Crispy golden fries with sea salt and ketchup',
                'price'             => 79.00,
                'food_type'         => 'veg',
                'is_bestseller'     => true,
                'prep_time_minutes' => 8,
                'tags'              => json_encode(['fries', 'veg', 'crispy']),
            ],
            [
                'category_id'       => 3,
                'name'              => 'Peri Peri Fries',
                'description'       => 'Crunchy fries seasoned with house peri peri spice blend',
                'price'             => 89.00,
                'food_type'         => 'veg',
                'is_featured'       => true,
                'prep_time_minutes' => 8,
                'tags'              => json_encode(['fries', 'spicy', 'peri-peri']),
            ],
            [
                'category_id'       => 3,
                'name'              => 'Loaded Cheese Fries',
                'description'       => 'Thick-cut fries smothered in melted cheddar cheese sauce and jalapenos',
                'price'             => 109.00,
                'food_type'         => 'veg',
                'is_bestseller'     => true,
                'prep_time_minutes' => 10,
                'tags'              => json_encode(['fries', 'cheese', 'loaded']),
            ],
            [
                'category_id'       => 3,
                'name'              => 'Masala Fries',
                'description'       => 'Desi-spiced fries tossed in chaat masala with coriander',
                'price'             => 89.00,
                'food_type'         => 'veg',
                'prep_time_minutes' => 8,
                'tags'              => json_encode(['fries', 'desi', 'masala']),
            ],
            [
                'category_id'       => 3,
                'name'              => 'Garlic Bread (4 pcs)',
                'description'       => 'Toasted baguette slices with herb garlic butter',
                'price'             => 69.00,
                'food_type'         => 'veg',
                'prep_time_minutes' => 7,
                'tags'              => json_encode(['snack', 'bread', 'veg']),
            ],

            /* ─── Maggi & Quick Bites (category_id: 4) ─── */
            [
                'category_id'       => 4,
                'name'              => 'Classic Masala Maggi',
                'description'       => 'The OG Maggi cooked with onion, tomato and the iconic masala',
                'price'             => 69.00,
                'food_type'         => 'veg',
                'is_bestseller'     => true,
                'prep_time_minutes' => 7,
                'tags'              => json_encode(['maggi', 'comfort food', 'veg']),
            ],
            [
                'category_id'       => 4,
                'name'              => 'Cheese Maggi',
                'description'       => 'Creamy Maggi topped with melted processed cheese',
                'price'             => 89.00,
                'food_type'         => 'veg',
                'is_featured'       => true,
                'prep_time_minutes' => 7,
                'tags'              => json_encode(['maggi', 'cheese']),
            ],
            [
                'category_id'       => 4,
                'name'              => 'Egg Maggi',
                'description'       => 'Classic Maggi topped with a runny fried egg',
                'price'             => 89.00,
                'food_type'         => 'non_veg',
                'prep_time_minutes' => 8,
                'tags'              => json_encode(['maggi', 'egg']),
            ],
            [
                'category_id'       => 4,
                'name'              => 'Veggie Loaded Maggi',
                'description'       => 'Maggi loaded with sweet corn, peas, capsicum and carrot',
                'price'             => 89.00,
                'food_type'         => 'veg',
                'prep_time_minutes' => 8,
                'tags'              => json_encode(['maggi', 'healthy', 'veg']),
            ],

            /* ─── Beverages (category_id: 5) ─── */
            [
                'category_id'       => 5,
                'name'              => 'Classic Lemonade',
                'description'       => 'Fresh-squeezed lemon juice with a hint of mint and sugar syrup',
                'price'             => 59.00,
                'food_type'         => 'veg',
                'is_bestseller'     => true,
                'prep_time_minutes' => 5,
                'tags'              => json_encode(['cold', 'refreshing', 'veg']),
            ],
            [
                'category_id'       => 5,
                'name'              => 'Mint Lemonade',
                'description'       => 'Zesty lemonade blended with fresh muddled mint leaves',
                'price'             => 69.00,
                'food_type'         => 'veg',
                'is_featured'       => true,
                'prep_time_minutes' => 5,
                'tags'              => json_encode(['cold', 'mint', 'refreshing']),
            ],
            [
                'category_id'       => 5,
                'name'              => 'Virgin Mojito',
                'description'       => 'Sparkling limeade with mint, crushed ice and a dash of soda',
                'price'             => 79.00,
                'food_type'         => 'veg',
                'is_bestseller'     => true,
                'prep_time_minutes' => 5,
                'tags'              => json_encode(['cold', 'mocktail', 'veg']),
            ],
            [
                'category_id'       => 5,
                'name'              => 'Watermelon Lemonade',
                'description'       => 'Fresh watermelon juice blended with lemon and a pinch of black salt',
                'price'             => 79.00,
                'food_type'         => 'veg',
                'prep_time_minutes' => 5,
                'tags'              => json_encode(['cold', 'fruit', 'seasonal']),
            ],
            [
                'category_id'       => 5,
                'name'              => 'Cold Brew Lemonade',
                'description'       => 'Cold brew coffee meets fresh lemonade — the ultimate refresher',
                'price'             => 99.00,
                'food_type'         => 'veg',
                'is_featured'       => true,
                'prep_time_minutes' => 5,
                'tags'              => json_encode(['cold', 'coffee', 'unique']),
            ],
            [
                'category_id'       => 5,
                'name'              => 'Mango Lassi',
                'description'       => 'Thick alphonso mango blended with chilled yogurt and a touch of cardamom',
                'price'             => 79.00,
                'food_type'         => 'veg',
                'prep_time_minutes' => 5,
                'tags'              => json_encode(['cold', 'dairy', 'mango']),
            ],

            /* ─── Coffee & Hot Drinks (category_id: 6) ─── */
            [
                'category_id'       => 6,
                'name'              => 'Espresso',
                'description'       => 'Single-origin espresso shot, bold and balanced',
                'price'             => 59.00,
                'food_type'         => 'veg',
                'prep_time_minutes' => 5,
                'tags'              => json_encode(['coffee', 'hot', 'strong']),
            ],
            [
                'category_id'       => 6,
                'name'              => 'Cappuccino',
                'description'       => 'Rich espresso topped with velvety steamed milk foam',
                'price'             => 89.00,
                'food_type'         => 'veg',
                'is_bestseller'     => true,
                'prep_time_minutes' => 5,
                'tags'              => json_encode(['coffee', 'hot', 'milk']),
            ],
            [
                'category_id'       => 6,
                'name'              => 'Café Latte',
                'description'       => 'Smooth espresso with a generous pour of steamed whole milk',
                'price'             => 99.00,
                'food_type'         => 'veg',
                'is_featured'       => true,
                'prep_time_minutes' => 5,
                'tags'              => json_encode(['coffee', 'hot', 'creamy']),
            ],
            [
                'category_id'       => 6,
                'name'              => 'Cold Coffee',
                'description'       => 'Chilled blended coffee with milk, ice and a scoop of vanilla ice cream',
                'price'             => 109.00,
                'food_type'         => 'veg',
                'is_bestseller'     => true,
                'prep_time_minutes' => 5,
                'tags'              => json_encode(['coffee', 'cold', 'creamy']),
            ],
            [
                'category_id'       => 6,
                'name'              => 'Hazelnut Latte',
                'description'       => 'Espresso with hazelnut syrup and steamed milk, topped with whipped cream',
                'price'             => 119.00,
                'food_type'         => 'veg',
                'prep_time_minutes' => 5,
                'tags'              => json_encode(['coffee', 'hazelnut', 'sweet']),
            ],
            [
                'category_id'       => 6,
                'name'              => 'Masala Chai',
                'description'       => 'Traditional Indian spiced tea brewed with ginger, cardamom and cinnamon',
                'price'             => 49.00,
                'food_type'         => 'veg',
                'is_featured'       => true,
                'prep_time_minutes' => 5,
                'tags'              => json_encode(['tea', 'hot', 'desi']),
            ],
        ];

        foreach ($items as $item) {
            DB::table('menu_items')->insert([
                'category_id'       => $item['category_id'],
                'name'              => $item['name'],
                'slug'              => Str::slug($item['name']),
                'description'       => $item['description'],
                'price'             => $item['price'],
                'discount_price'    => null,
                'food_type'         => $item['food_type'],
                'is_available'      => true,
                'is_featured'       => $item['is_featured'] ?? false,
                'is_bestseller'     => $item['is_bestseller'] ?? false,
                'prep_time_minutes' => $item['prep_time_minutes'],
                'tags'              => $item['tags'] ?? null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ]);
        }
    }
}
